### ISSUE TITLE
Not an example of `Use constructor chaining as an example.`

### ISSUE THREAD

**Issue by roskelleycj** [barbozalg/badges#12]
This:
https://github.com/barbozalg/badges/blob/c6d1a78cc25ca56bc598273836a444823f605f56/java/apprentice/overloadconstructors/src/main/java/com/barbozalg/overloadconstructors/Card.java#L18-L34

Does not show an example of constructor chaining.  This is a proper example of constructor chaining:
```
    public Card(int value, CardType type) throws Exception {
      this(value, type, "Black");
    }

    public Card(int value, CardType type, String reverseBackGround) throws Exception {
        this.type = type;
        this.setColor();
        this.setValue(value);
        this.reverseBackGround = reverseBackGround;
        this.setCovered(true);
        this.backGround = "White";
    }
```

**Comment by barbozalg** [comment]
Thank you, now I understand what is a constructor chaining.

**Comment by barbozalg** [comment]
https://github.com/barbozalg/badges/pull/15/commits/8a7bd47f95367b1ccfee7d01f17de9bbd31b0eb8
