### ISSUE TITLE
Missing the exception in the log output

### ISSUE THREAD

**Issue by roskelleycj** [barbozalg/badges#13]
This:
https://github.com/barbozalg/badges/blob/c6d1a78cc25ca56bc598273836a444823f605f56/java/apprentice/totalcharacters/src/main/java/com/barbozalg/totalcharacters/TotalCharacters.java#L71

Shows an opportunity for learning.  In that anytime we add a try/catch we also need to consider logging the exception.  Often times it looks like it is a known issue and we don't need to include it.  However, we also often don't know what details were included in the exception and could prove valuable in the diagnoses of a problem.  This is the proper approach:

```
LOGGER.error(msg, e);
```

**Comment by barbozalg** [comment]
Totally correct. I usually do it, but I forgot it here.
In addition to the message and the error, I usually add Markers (other value pairs) that could be necessary according to the case.

**Comment by barbozalg** [comment]
https://github.com/barbozalg/badges/pull/15/commits/0707bd4699c48399d565c5aa26b368f75e1b4a79
