### ISSUE TITLE
Using logging specifiers

### ISSUE THREAD

**Issue by roskelleycj** [barbozalg/badges#14]
This could be an example:
https://github.com/barbozalg/badges/blob/c6d1a78cc25ca56bc598273836a444823f605f56/java/apprentice/totalcharacters/src/main/java/com/barbozalg/totalcharacters/TotalCharacters.java#L52

of where 'logging specifiers' could be used.  I.e., 
```
LOGGER.info("Current count: {}", i);
```

The logging framework has special logic that can really help in creating logs that are efficient and formatted consistently.

Additionally, as you learn about splunk you will also learn that json or key/value pairs are preferred.  I.e.,
```
LOGGER.info("Current count={}", i);
```

**Comment by barbozalg** [comment]
You are right. I modified it, I did it using String.format but I do not know how to do it in the way you showed in the example.

**Comment by barbozalg** [comment]
https://github.com/barbozalg/badges/pull/15/commits/372ee2c20661aff19a7e74412ce648e269616df1
